# Generated by Django 5.2.8 on 2025-12-11 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the international E.164 format: '+CCXXXXXXXXX'. Up to 15 digits allowed.", regex='^\\+\\d{7,15}$')]),
        ),
    ]
