# Generated by Django 5.2.8 on 2025-12-11 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApi', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the international E.164 format: '+CCXXXXXXXXXX'. The number must be 10 digits long after the country code.", regex='^\\+\\d{1,3}\\d{10}$')]),
        ),
    ]
