"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    'SECRET_KEY', default='django-insecure-0o#74yav1o3_&pj%2v5q=@z$n!)5z9)$14q$g90#39l)j7)s!0')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ['*']

# cors configuration
CORS_ALLOW_ALL_ORIGINS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'authApi',
    'walletApi',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/lagos'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'authApi.CustomUser'

# media configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Password validation for 6-digit PIN
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        }
    },
]

# JWT Settings

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# OpenAI API Configuration
OPENAI_API_KEY = config('OPENAI_API_KEY', default='')
OPENAI_MODEL = config('OPENAI_MODEL', default='gpt-4')
OPENAI_MAX_TOKENS = config('OPENAI_MAX_TOKENS', default=500, cast=int)

PAYSTACK_LIVE_SECRET_KEY = config('PAYSTACK_LIVE_SECRET_KEY', default='')
PAYSTACK_LIVE_PUBLIC_KEY = config('PAYSTACK_LIVE_PUBLIC_KEY', default='')

PAYSTACK_SECRET_KEY = PAYSTACK_LIVE_SECRET_KEY
PAYSTACK_PUBLIC_KEY = PAYSTACK_LIVE_PUBLIC_KEY


PAYSTACK_CALLBACK_URL = config(
    'PAYSTACK_CALLBACK_URL', default='http://localhost:4200/payment/callback')

# Base URL for API calls
PAYSTACK_BASE_URL = config(
    'PAYSTACK_BASE_URL', default='https://api.paystack.co')

PAYSTACK_WEBHOOK_SECRET = config('PAYSTACK_WEBHOOK_SECRET', default='')

# Paystack Callback URL is mostly for web, less critical for mobile SDK integration
PAYSTACK_CALLBACK_URL = config(
    'PAYSTACK_CALLBACK_URL', default='http://localhost:4200/payment/callback')

# DRF Spectacular (Swagger) Configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'Swift Wallet API',
    'DESCRIPTION': '''
    # Welcome to Swift Wallet API Documentation

    A comprehensive fintech API for mobile wallet management, featuring:

    ## 🔐 Authentication & Security
    - Phone number-based authentication with OTP
    - JWT token authentication
    - Device fingerprinting for one-device policy
    - Face verification using AI
    - Transaction PIN for secure payments

    ## 💰 Wallet Management
    - Mock wallet with starting balance
    - Send/receive money between users
    - Add money simulation
    - Transaction history with filtering
    - Real-time balance updates

    ## 💳 Bill Payments
    - Airtime & data purchases
    - Electricity bill payments
    - Cable TV subscriptions

    ## 📊 Analytics & Insights
    - Daily transaction summaries
    - Spending patterns analysis
    - Transaction categorization
    - Custom date range reports

    ## 🤖 AI Customer Service
    - GPT-4 powered intelligent support
    - Context-aware responses
    - Session continuity
    - Sentiment analysis

    ## 🔗 Getting Started

    1. **Sign Up**: Request OTP for your phone number
    2. **Verify**: Complete signup with OTP verification
    3. **Login**: Get your JWT access token
    4. **Use API**: Include token in Authorization header

    ## 📝 Authentication

    Most endpoints require JWT authentication. Include the token in your requests:

    ```
    Authorization: Bearer <your_access_token>
    ```

    ## 🎯 API Response Format

    All responses follow this structure:

    ```json
    {
      "status": "success|error",
      "message": "Description of the result",
      "data": { ... }
    }
    ```

    ## 📱 Demo Mode

    This is a simulation environment:
    - No real money transactions
    - OTP codes are returned in responses for testing
    - Starting balance: $1000 USD
    - All payments are simulated

    ---

    For support or questions, use the AI customer service endpoint!
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'TAGS': [
        {'name': 'Authentication',
            'description': 'User signup, login, and session management'},
        {'name': 'User Profile',
            'description': 'Profile management and personal information'},
        {'name': 'Face Verification', 'description': 'AI-powered identity verification'},
        {'name': 'Wallet', 'description': 'Wallet balance and account information'},
        {'name': 'Transactions',
            'description': 'Send money, add funds, and transaction history'},
        {'name': 'Bill Payments',
            'description': 'Airtime, data, electricity, and cable TV payments'},
        {'name': 'Security', 'description': 'Transaction PIN and security settings'},
        {'name': 'Beneficiaries', 'description': 'Manage saved recipients'},
        {'name': 'Analytics', 'description': 'Transaction analytics and insights'},
        {'name': 'AI Support', 'description': 'AI-powered customer service chatbot'},
        {'name': 'Dashboard', 'description': 'Summary and overview data'},
    ],
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api/',
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'filter': True,
        'tryItOutEnabled': True,
        'syntaxHighlight.theme': 'monokai',
        'defaultModelsExpandDepth': 2,
        'defaultModelExpandDepth': 2,
        'docExpansion': 'list',
        'tagsSorter': 'alpha',
        'operationsSorter': 'alpha',
    },
    'SWAGGER_UI_DIST': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest',
    'SWAGGER_UI_FAVICON_HREF': 'https://fastapi.tiangolo.com/img/favicon.png',
    'REDOC_DIST': 'https://cdn.jsdelivr.net/npm/redoc@latest',
    'SECURITY': [
        {
            'bearerAuth': []
        }
    ],
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'bearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
                'description': 'Enter your JWT access token obtained from login'
            }
        }
    },
    'PREPROCESSING_HOOKS': [],
    'POSTPROCESSING_HOOKS': [],
    'SERVERS': [
        {
            'url': 'http://localhost:8000',
            'description': 'Development server'
        },
        {
            'url': 'http://localhost:4200',
            'description': 'Angular frontend (CORS enabled)'
        }
    ],
    'CONTACT': {
        'name': 'Swift Wallet Support',
        'email': 'support@swiftwallet.demo'
    },
    'LICENSE': {
        'name': 'MIT License'
    },
}


# AWS SNS Configuration
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='')
AWS_REGION_NAME = config('AWS_REGION_NAME', default='eu-north-1')
