# Generated by Django 5.2.8 on 2025-12-16 12:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('INFO', 'Info'), ('PROMO', 'Promo')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail_url', models.URLField(help_text='URL to the promo image (stored on S3 or media server)', max_length=500)),
                ('action_type', models.CharField(choices=[('DEEP_LINK', 'Deep Link'), ('WEB_URL', 'Web URL'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('action_link', models.TextField(blank=True, help_text='Deep link path (e.g., /top-up) or full URL')),
                ('is_active', models.BooleanField(default=True, help_text='Only active promos are shown to users')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first in the carousel')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional: Promo expires after this date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin user who created this promo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('CLICK', 'Click'), ('DISMISS', 'Dismiss'), ('VIEW', 'View')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='notificationApi.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_interactions', to=settings.AUTH_USER_MODEL)),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='notificationApi.promotion')),
            ],
            options={
                'verbose_name': 'Notification Interaction',
                'verbose_name_plural': 'Notification Interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='promotion',
            field=models.ForeignKey(blank=True, help_text='Link to promotion if this is a promo notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notificationApi.promotion'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active', 'display_order'], name='notificatio_is_acti_460cce_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['start_date', 'end_date'], name='notificatio_start_d_448996_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationinteraction',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_8b2d52_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationinteraction',
            index=models.Index(fields=['promotion', 'interaction_type'], name='notificatio_promoti_00572c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_e2aca9_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read'], name='notificatio_user_id_c0ddd7_idx'),
        ),
    ]
